apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNTVhKdzA5bjRZNlNEbzc0ODgvCkkyYW41QU9WV1h0QlR6NDZOd1F0Y2s5VHozZk5YQVVqUUlFTUN3RXRub2ZpWHgvWSs2c3VjK1BBRk1mR3JsUlgKMU00QTVvZHg2S01xbmZmbkdlT3RCTVFZcTVxTWZ4b1FHNWUwb1NoY0tHZGJ0SDJQWEFhU0NxakpEQ0JIOHpFWAp5SDZZcHBuWHlNZk51Yzh3VjVwZkl3OVBrcFlSb3FPbEZaWWJDYzBkTG1RMmhpVGVCMEdBd1E3SHJXMWkxaW5zCmI4YVJCUEcybERhODVFczRkY0wrU3B4eUFlakZwbUlPeDloZ2I4Mld3NzNOUkdoQkdKaEJzSEdkWUlHYmFXSHIKaVZMd3dVVEpiamZOOW5YeW1WTDJyK0JUNnoyS0UwM3BHekV6V1RwU0g2eWlqUGdpSkNsUUZ0a0Q1c3pFamx6SwpmL2NDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE3MEtxN0szUnpRQ3Z0QXowdWptUEZRenhHCi9McVFFNVJKTzcyZnRrcXZDd3ExMzFxdlpIcVRZZDZ5QXUwMmpkVEdsVjJXQTBseVV2ejR5b2taN29UcEttSG0KS1VWTDhFUFgwVUdndEdrVDJBeGN1K2o4QUJvTmxJYTQrcitxU1IrTUVPQmRrYlRYZlcyN3BWWFdUUFVVeG90cwpYTk5mWGR2aTkzSmpVTy85S2ZiclJET3lncnJtd1YzcGFtMGRLYXM2Wi9SbVh3dnUxRTNiWU4wZVhVZC85M1hOCkw1RUZSNVNkYzNmdHQveXBUc3Y4L1lINjRnbU93VSs0YzJUS2ZCMFhnOUNZZ2pHVEFrWVJicVJDaldDMGl3ZEYKTVZtb285ZWo5OEpJQ2hBeW5qbzE2azdsSU5LNnlxOEIzclcrUGcxRnRoKy9tMEZpdFJkaHQxaDBoRHJRCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
